config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, controllers: {application: 'application', instagram: 'instagram', photos: 'photos' }
 
  get 'instagram/auth', to: 'instagram#auth'

  resources :photos do
  	collection do
  		get 'saved'
  		post 'save_order'
  	end
  end

  get 'users_followed/index'
  # post 'users_followed/suggest'
  get 'users_followed/followers'
  get 'users_followed/following'
  get 'users_followed/unfollow'
  post 'users_followed/insta_unfollow'

end

app/controllers/users_followed_controller.rb
class UsersFollowedController < ApplicationController

  before_action :get_token  #, :except => [:create, :update, :destroy]

  def index
  	
    # Get users following me
    @followers_response = get_followers()
    @followers_num = @followers_response['data'].length

    
    # Get users i'm following
    @following_response = get_following()
    @following_num = @following_response['data'].length

    # Get "Not following me back" 
    @not_following = @following_response['data'] - @followers_response['data']
    @not_following_num = @not_following.length

  end

  def followers
    @followers = get_followers()
  end

  def following
    @following = get_following()
  end

  def unfollow
    @followers = get_followers()
    @following = get_following()
    @following_not = @following['data'] - @followers['data']
  end

  def insta_unfollow
    if params[:user_id]
      @user_id = params[:user_id].to_i
      @access_token = @token["access_token"]
      @parameters = {'access_token' => @insta_account.token, 'action' => 'unfollow'}

      url = "https://api.instagram.com/v1/users/#{@user_id}/relationship";
      uri = URI(url)
      form_data = URI.encode_www_form(@parameters)

      Net::HTTP.start(uri.host, uri.port,
        :use_ssl => uri.scheme == 'https') do |http|
        request = Net::HTTP::Post.new uri
        request.body = form_data
        response = http.request request 
        @unfollow_response = JSON.parse(response.body)
      end

      render json: @unfollow_response

    end
  end

  def insta_follow
    if params[:user_id]
      @user_id = params[:user_id].to_i
      @access_token = @token["access_token"]
      @parameters = {'access_token' => @insta_account.token, 'action' => 'follow'}

      url = "https://api.instagram.com/v1/users/#{@user_id}/relationship";
      uri = URI(url)
      form_data = URI.encode_www_form(@parameters)

      Net::HTTP.start(uri.host, uri.port,
        :use_ssl => uri.scheme == 'https') do |http|
        request = Net::HTTP::Post.new uri
        request.body = form_data
        response = http.request request 
        @follow_response = JSON.parse(response.body)
      end

      render json: @follow_response

    end
  end

  # def suggest
  #   if params[:data]
  #     tag = params[:data]

  #     # Search insta hashtag
  #     insta_account = InstaAccount.find_by(user_id: current_user.id)
  #     uri = URI("https://api.instagram.com/v1/tags/#{tag}/media/recent/")
  #     params = {'access_token' => insta_account.token}
  #     uri.query = URI.encode_www_form(params)

  #     Net::HTTP.start(uri.host, uri.port,
  #       :use_ssl => uri.scheme == 'https') do |http|
  #       request = Net::HTTP::Get.new uri
  #       response = http.request request 
  #       @tag_response = JSON.parse(response.body)
  #     end

  #     @suggested_followers = []
  #     @tag_response['data'].each do |data|
  #       @suggested_followers << {id: data["user"]["id"], username: data["user"]["username"]}
  #     end

  #     @unique_followers = @suggested_followers.uniq { |hash| hash[:id] }

  #   end
  # end

  private

    def get_token
      @insta_account = InstaAccount.find_by(user_id: current_user.id)
      @token = {'access_token' => @insta_account.token}
    end

    def http_request(uri)
      Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
        request = Net::HTTP::Get.new uri
        response = http.request request 
        return json = JSON.parse(response.body)
      end
    end

    def get_followers()
      uri = URI('https://api.instagram.com/v1/users/self/followed-by/')
      uri.query = URI.encode_www_form(@token)
      return http_request(uri)
    end

    def get_following()
      uri = URI('https://api.instagram.com/v1/users/self/follows/')
      uri.query = URI.encode_www_form(@token)
      return http_request(uri)
    end

end

app/helpers/users_followed_helper.rb
module UsersFollowedHelper
end

app/views/users_followed/followers.html.erb
<%= render "layouts/container-start" %>
  <div class="padding-container">
	<h1>Followers</h1>
		<ul class="list-group">
			<% @following_response['data'].each do |array| %>
				<form action="" class="form-inline">
					<%= image_tag(array["profile_picture"], size: "35", class: "d-inline") %>
					<span><%= array["username"] %></span>
					<!-- <label for="<%= array["id"] %>"><%= array["username"] %></label> -->
					<input type="text" class="hidden" name="id" id="<%= array["id"] %>" value="<%= array["id"] %>">
					<button type="submit" class="btn btn-default">Unfollow</button>
				</form>

<!-- 				  <li class="list-group-item">
				  	<span><%= array["username"] %></span>
				  	<a href="<%= "#" %>" class="btn btn-primary" role="button">Unfollow</a>
				  </li> -->
		    <% end %>
    	</ul>

<%= render "layouts/container-end" %>

app/views/users_followed/following.html.erb
<%= render "layouts/container-start" %>
  <div class="padding-container followers">
	<h1>I'm Following</h1>
		<ul class="list-group">
			<% @following['data'].each do |array| %>
				<form action="" class="form-inline">
					<%= image_tag(array["profile_picture"], size: "50", class: "d-inline img-circle") %>
					<span><%= array["username"] %></span>
					<input type="text" class="hidden" name="id" id="<%= array["id"] %>" value="<%= array["id"] %>">
					<button id="unfollow" type="submit" class="btn btn-default pull-right btn-success">Unfollow</button>
				</form>
		    <% end %>
    	</ul>
  </div>
<%= render "layouts/container-end" %>

app/views/users_followed/index.html.erb
<%= render "layouts/container-start" %>
  <div class="padding-container">
    <h1>Follower Summary</h1>
    <a href="<%= users_followed_followers_path %>" class="btn btn-primary btn-lg btn-block btn-followers" role="button">Following Me<span style="float: right;"><%= @followers_num %></span></a>

	<a href="<%= users_followed_following_path %>" class="btn btn-primary btn-lg btn-block btn-followers" role="button">I'm Following<span class="pull-right"><%= @following_num %></a>

	<a href="<%= users_followed_unfollow_path %>" class="btn btn-primary btn-lg btn-block btn-followers" role="button">
	  Not following me back<span class="pull-right"><%= @not_following_num %></span>
	</a>

<!-- 	<h2 class="mtl">Find Followers By Hashtag</h2>
	<input type="text" id="hashtag-text" class="form-control" placeholder="Enter tag without hash in front"><br>
	<button id="find-followers" class="btn btn-primary" type="button">Find Followers</button>
	<br><br>
	<div class="spinner"><br><%= image_tag("ajax-loader.gif") %></div>
	<div id="follower-list"></div>
  </div> -->
<%= render "layouts/container-end" %>

app/views/users_followed/suggest.html.erb
<% if @unique_followers.empty? %>
	<p>Sorry, we found no Instagram users for that hashtag</p>
<% else %>
	<% @unique_followers.each do | follower | %>
		<span style="line-height: 250%; padding-left: 10px;"><%= follower[:username] %></span>
		<button type="button" class="btn btn-primary pull-right">Follow</button>
	<% end %>
<% end %>

app/views/users_followed/unfollow.html.erb
<%= render "layouts/container-start" %>
  <div class="padding-container followers">
	<h1>Not Following Me Back</h1>
		<ul class="list-group">
			<% @following_not.each do |array| %>
				<div class="follower-display">
					<%= image_tag(array["profile_picture"], size: "50", class: "d-inline img-circle") %>
					<span><%= array["username"] %></span>
					<span id="spinner-<%= array["id"] %>" class="spinner pull-right"><%= image_tag("ajax-loader.gif") %></span>
					<button id="<%= array["id"] %>" type="button" class="btn btn-default pull-right btn-success unfollow">Unfollow</button>
					<span id="error-msg" class="pull-right hidden">Sorry, an error occurred</span>
				</div>
		    <% end %>
    	</ul>
<!--       <input type="text" class="hidden" id="account_token" value="<%= @insta_account.token %>"> -->
  </div>
<%= render "layouts/container-end" %>