config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, controllers: {application: 'application', instagram: 'instagram', photos: 'photos' }
 
  get 'instagram/auth', to: 'instagram#auth'

  resources :photos do
  	collection do
  		get 'saved'
  		post 'save_order'
  	end
  end

  get 'users_followed/index'
  # post 'users_followed/suggest'
  get 'users_followed/followers'
  get 'users_followed/following'
  get 'users_followed/unfollow'
  post 'users_followed/insta_unfollow'

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  mount_uploader :url, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  require 'net/http'
  require 'json'

  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  # before_action :account_info

  # show all saved photos, without showing instagram photos
  def saved
    @saved_photos = Photo.where(user_id: current_user.id)    
  end

  # post to save the photo order
  def save_order
    if params[:position]
      @photos_to_order = Photo.find(params[:position])
      i = 1
      @photos_to_order.each do |photo|
        photo.update(position: i)
        i += 1
      end
    end
  end

  # GET /photos (show the feed)
  def index
    @photos = Photo.select(:id, :url).where(user_id: current_user.id).where(status: 'pending').order(:position)
    @user = User.find_by(id: current_user.id)

    # Get insta account info
    insta_account = InstaAccount.find_by(user_id: current_user.id)
    uri = URI('https://api.instagram.com/v1/users/self/')
    params = {'access_token' => insta_account.token}
    uri.query = URI.encode_www_form(params)

    Net::HTTP.start(uri.host, uri.port,
      :use_ssl => uri.scheme == 'https') do |http|
      request = Net::HTTP::Get.new uri
      response = http.request request 
      @account = JSON.parse(response.body)
    end

    @account_info = {}
    @account_info.store(:username, @account["data"]["username"])
    @account_info.store(:full_name, @account["data"]["full_name"])
    @account_info.store(:bio, @account["data"]["bio"])
    @account_info.store(:profile_picture, @account["data"]["profile_picture"])
    @account_info.store(:posts, @account["data"]["counts"]["media"])
    @account_info.store(:followed_by, @account["data"]["counts"]["followed_by"])
    @account_info.store(:following, @account["data"]["counts"]["follows"])

    # Get insta photos
    insta_account = InstaAccount.find_by(user_id: current_user.id)
    uri = URI('https://api.instagram.com/v1/users/self/media/recent/')
    params = {'access_token' => insta_account.token, 'count' => 12}
    uri.query = URI.encode_www_form(params)

    Net::HTTP.start(uri.host, uri.port,
      :use_ssl => uri.scheme == 'https') do |http|
      request = Net::HTTP::Get.new uri
      response = http.request request 
      @insta_response = JSON.parse(response.body)
    end

    @insta_photos = []
    @insta_response['data'].each do |array|
    @insta_photos << array['images']['low_resolution']['url']
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    redirect_to action: "saved"
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_path, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:caption, :status, :position, :photo_credit, :url, :user_id)
    end

    # def account_info
    #     @account = InstaAccount.find(current_user.id)
    # end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  	<div class="container col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
		<div class="row app-footer">
			<div class="col-xs-3 col-sm-3 col-md-3"><%= link_to "<i class='fa fa-plus-square' aria-hidden='true'></i>".html_safe, new_photo_path %></div>
			<div class="col-xs-3 col-sm-3 col-md-3 text-center"><%= link_to "<i class='fa fa-user' aria-hidden='true'></i>".html_safe, users_followed_index_path %></div>
			<div class="col-xs-3 col-sm-3 col-md-3 text-center"><%= link_to "<i class='fa fa-th' aria-hidden='true'></i>".html_safe, photos_path %></div>
			<div class="col-xs-3 col-sm-3 col-md-3 text-right"><%= link_to "<i class='fa fa-picture-o' aria-hidden='true'></i>".html_safe, saved_photos_path %></div>
		</div>
	</div>
</nav>

app/views/photos/_header.html.erb
<nav class="navbar navbar-default">
  	<div class="container col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
		<div class="row" id="app-header">
			<div class="col-xs-4 col-sm-4 col-md-4"><p class="logo">FEEDSTA</p></div>
			<div class="col-xs-4 col-sm-4 col-md-4 photos-head-center"><p class="insta-handle"> <!-- <i class="fa fa-caret-down" aria-hidden="true"></i> --></p></div>
			<div class="col-xs-4 col-sm-4 col-md-4 photos-head-right"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "settings" %> </div>
		</div>
	</div>
 </nav>

app/views/photos/edit.html.erb
<%= render "layouts/container-start" %>
<div class="panel">
	<div class="panel-body">
		<h1>Edit Photo</h1>
		<div class="col-xs-12 col-sm-12 col-md-12 phn">
			<%= image_tag (@photo.url_url(:standard)), class: "col-xs-6 col-sm-6 col-md-4 mvl phn" %>
		</div>
		<%= button_to "Delete Photo", photo_path, :class => "btn btn-danger mtm mbl", :method => :delete, data: {confirm: "Are you sure you want to permanently delete this photo?"} %>
		
		<%= simple_form_for @photo, html: {multipart: true} do |f| %>
		  <%= f.error_notification %>

		  <div class="form-inputs">
		    <label>Show photo in feed &nbsp;&nbsp;&nbsp;&nbsp;</label>
		    <%= f.collection_radio_buttons :status, [['saved', 'No'], ['pending', 'Yes']], :first, :last %>
		    <%= f.input :caption, :input_html => {:rows => 12} %>
		    <%= f.input :photo_credit %>
		    <%= f.input :url, as: :file, label: "Select New Photo" %>
		  </div>
		  <br>
		  <div class="form-actions">
		    <%= f.button :submit, "Save Photo", class: "btn-success" %>
		  </div>
		<% end %>

	</div>
</div>
<%= render "layouts/container-end" %>

app/views/photos/index.html.erb
<%= render "layouts/container-start" %>

<!--     <p id="notice"><%= notice %></p> -->

<div class="row account-info">
	<div class="col-xs-4 col-sm-4 col-md-4">
		<%= image_tag(@account_info[:profile_picture], class: "img-circle", height: 100, width: 100) %>
	</div>
	<div class="col-xs-8 col-sm-8 col-md-8 account-stats">
<!-- 		<h1><%= @account_info[:username] %></h1> -->
    <div class="col-xs-4 col-sm-4 col-md-4">
      <h6><strong><%= @account_info[:posts] %></strong></h6>
      <p>posts</p>
    </div>

    <div class="col-xs-4 col-sm-4 col-md-4">
      <h6><strong><%= @account_info[:followed_by] %></strong></h6>
      <p class="text-center">followers</p>
    </div>

    <div class="col-xs-4 col-sm-4 col-md-4">
      <h6><strong><%= @account_info[:following] %></strong></h6>
      <p class="text-center">following</p>
    </div>

    <button id="save-photo-order" type="button" class="btn save-order-btn mbl">Save Photo Order</button>
  </div>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 account-bio">
    <h4><%= @account_info[:full_name] %></h4>
		<p><%= @account_info[:bio] %></p>
	</div>
</div>

 <div id="sortable" class="photo-grid">
  <% unless @photos.blank? %>	
      <% @photos.each do |photo| %>
        <div id="position_<%= photo.id %>" class="photo-wrapper col-xs-4 col-sm-4 col-md-4" style="background-image: url(<%= photo.url_url(:standard)%>); background-size: cover; float: left; width: 32.2%">
      		<a href="<%= edit_photo_path(id: photo.id) %>">
            <i class="fa fa-picture-o fa-2x pull-right" aria-hidden="true" style="color: black; margin: 5px;"></i>
          </a>
      	</div> 
      <% end %>
  <% end %>
</div>  
<div>
  <% unless @insta_photos.blank? %>
    <% @insta_photos.each do |photo| %>
      <div class="photo-wrapper col-xs-4 col-sm-4 col-md-4" style="background-image: url(<%= photo %>); background-size: cover; float: left; width: 32.2%">
      </div>
      <!-- <div class="photo-wrapper col-xs-4 col-sm-4 col-md-4">
        <img src=<%= photo %> class="img-responsive" >
      </div>  -->
    <% end %>
  <% end %>
</div> 
<%= render "layouts/container-end" %>

app/views/photos/new.html.erb
<%= render "layouts/container-start" %>
<div class="panel">
	<div class="panel-body">
		<h1 class="mtn">Add New Photo</h1>
		
		<%= simple_form_for @photo, html: {multipart: true} do |f| %>
		  <%= f.error_notification %>
		  <div class="form-inputs">
		    <label>Show photo in feed &nbsp;&nbsp;&nbsp;&nbsp;</label>
		    <%= f.collection_radio_buttons :status, [['saved', 'No'], ['pending', 'Yes']], :first, :last %>
		    <%= f.input :caption, :input_html => {:rows => 12} %>
		    <%= f.input :photo_credit %>
		    <%= f.input :url, as: :file, label: "Select New Photo", required: true %>
		  </div>
		  <br>
		  <div class="form-actions">
		    <%= f.button :submit, "Save Photo", class: "btn-success" %>
		  </div>
		<% end %>

	</div>
</div>
<%= render "layouts/container-end" %>

app/views/photos/saved.erb
<%= render "layouts/container-start" %>
  <div class="padding-container">
    <h1>Saved Photos</h1>
    <p id="notice"><%= notice %></p>
    </div> 
	<div class="row photo-grid">
	  <% unless @saved_photos.blank? %>	
	      <% @saved_photos.each do |photo| %>
	      	<a href="<%= edit_photo_path(id: photo.id) %>">
	           <div class="photo-wrapper col-xs-4 col-sm-4 col-md-4" style="background-image: url(<%= photo.url_url(:standard)%>); background-size: cover; float: left; width: 32.2%"></div>
	        </a>
	      <% end %>
	  <% end %>
  </div> 
<%= render "layouts/container-start" %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>

<p>
  <strong>Status:</strong>
  <%= @photo.status %>
</p>

<p>
  <strong>Position:</strong>
  <%= @photo.position %>
</p>

<p>
  <strong>Photo credit:</strong>
  <%= @photo.photo_credit %>
</p>

<p>
  <strong>File:</strong>
  <%= @photo.url %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>